general:
  result_path: benchmark-output-data-set-1-06-08-2019
  result_as_json: True
  result_as_csv: True
  test_timeout: 300
  global_working_directory: .
  translator_cache_dir: /tmp

translators:
  - from_format: TPTP
    to_format: LADR
    command: ../provers/LADR-2009-11A/bin/tptp_to_ladr
    input_as_stdin: True
    output_as_stdout: True

test_inputs:
  - name: example_input1
    cwd: ../logit-formula-generator/test_data/data_set_1/
    files:
      - '*.p'
    format: TPTP
  - name: example_input2
    cwd: ../logit-formula-generator/test_data/data_set_2/
    files:
      - '*.p'
    format: TPTP

test_suites:
  - name: Prover9 test suite
    command: ../provers/LADR-2009-11A/bin/prover9
    input_as_stdin: True
    version: 2009-11A
    required_format: LADR
    save_stdout: False
    save_stderr: True
  - name: SPASS test suite
    command: ../provers/spass39/SPASS -PStatistic=0 -PGiven=0 -DocProof=0 -PProblem=0 -TPTP
    input_as_stdin: True
    required_format: TPTP
    version: "3.9"
    save_stdout: True
    save_stderr: True
