[general]
# generate output to
output_dir="benchmark-prover9-spass.json"
test_case_timeout = 300

[[translators]]
from_format="TPTP"
to_format="LADR"
extension="in"
PATH="../provers/LADR-2009-11A/bin"
executable="tptp_to_ladr"
options=[]
#input_after_option="-TPTP"
#input_as_last_argument=false
#output_after_option=""

#[[testInputs]]
## for specifying include/exclude in testCase
#name="tptp 1 2 3 4 5-SAT"
#path=""
## wildcards supported
#files=["gen-3-dim/*.p"]
## currently only TPTP
#format="TPTP"

[[testInputs]]
name="set_1"
path="../logit-formula-generator/test_data/data_set_1/"
files=["*.p"]
format="TPTP"

[[testInputs]]
name="set_2"
path="../logit-formula-generator/test_data/data_set_2/"
files=["*.p"]
format="TPTP"


# PROVER9
[[testSuites]]
name="Prover9 test suite"
# name available in PATH
executable="prover9"
# append to path env variable, comment or leave empty to disable
PATH="../provers/LADR-2009-11A/bin"
version="2009-11A"
capture_stdout=false
# options always appended to executable, comment or leave empty to disable
#options=[""]

[[testSuites.testRuns]]
name="Prover9 test set_1"
format="LADR"
include_only=["set_1"]
#exclude=["set_1", "set_2"]
options=[]

[[testSuites.testRuns]]
name="Prover9 test set_2"
format="LADR"
options=[]
include_only=["set_2"]
#exclude=["set_1", "set_2"]

# SPASS
[[testSuites]]
name="SPASS test suite"
executable="SPASS"
PATH="../provers/spass39/"
version="3.9"
capture_stdout=true
options=["-PStatistic=0", "-PGiven=0", "-DocProof=0", "-PProblem=0"]

[[testSuites.testRuns]]
name="SPASS test set_1"
format="TPTP"
options=[]
input_after_option="-TPTP"
include_only=["set_1"]
#exclude=["set_1", "set_2"]

[[testSuites.testRuns]]
name="SPASS test set_2"
format="TPTP"
options=[]
input_after_option="-TPTP"
include_only=["set_2"]
#exclude=["set_1", "set_2"]




